version: '3.8'

services:
  app:
    build: 
      context: .
    ports:
      - 8000:8000
    environment:
      - DB_URL=postgresql://${DB_USER}:${DB_PASSWORD}@database:5432/${DB_DATABASE}
    depends_on:
      - database
    restart: on-failure


  database:
    image: postgres
    container_name: postgres
    ports:
      - 5435:5432

    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
