version: '3.8'

services:
  app:
    build: 
      context: .
    ports:
      - 8000:8000
    environment:
      - DB_URL=postgresql://postgres:marmaidarmy@postgres:5432/fastapi
    depends_on:
      - database
    restart: on-failure


  database:
    image: postgres
    container_name: postgres
    ports:
      - 5435:5432

    environment:
      - POSTGRES_DB=fastapi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=marmaidarmy
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
